
[2021-06-17 16:44:00] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py39.V8FunctionHandler_Execute
  File "c:\Users\craig\Documents\Python\Youtube-Downloader\V2\main.py", line 8, in create_instance
    data = vid.get_meta()
  File "c:\Users\craig\Documents\Python\Youtube-Downloader\V2\YTDL_classes.py", line 51, in get_meta
    self.__set_meta(self.__yt)
  File "c:\Users\craig\Documents\Python\Youtube-Downloader\V2\YTDL_classes.py", line 41, in __set_meta
    stream = yt.streams
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 308, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 213, in fmt_streams
    if "adaptive_fmts" in self.player_config_args:
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 187, in player_config_args
    self._player_config_args = self.vid_info
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 278, in vid_info
    return dict(parse_qsl(self.vid_info_raw))
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 108, in vid_info_raw
    self._vid_info_raw = request.get(self.vid_info_url)
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\request.py", line 52, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\request.py", line 36, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found


[2021-06-17 16:44:59] Traceback (most recent call last):
  File "v8function_handler.pyx", line 48, in cefpython_py39.V8FunctionHandler_Execute
  File "c:\Users\craig\Documents\Python\Youtube-Downloader\V2\main.py", line 8, in create_instance
    data = vid.get_meta()
  File "c:\Users\craig\Documents\Python\Youtube-Downloader\V2\YTDL_classes.py", line 51, in get_meta
    self.__set_meta(self.__yt)
  File "c:\Users\craig\Documents\Python\Youtube-Downloader\V2\YTDL_classes.py", line 41, in __set_meta
    stream = yt.streams
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 308, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 213, in fmt_streams
    if "adaptive_fmts" in self.player_config_args:
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 187, in player_config_args
    self._player_config_args = self.vid_info
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 278, in vid_info
    return dict(parse_qsl(self.vid_info_raw))
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 108, in vid_info_raw
    self._vid_info_raw = request.get(self.vid_info_url)
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\request.py", line 52, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\request.py", line 36, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\craig\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

